


DECLARE @UNIVERSO_1 FLOAT, @CANTIDAD_APROBADOS_1 FLOAT, @CANTIDAD_REPROBADOS_1 FLOAT
EXEC ESTADISTICO_POR_PESO @CODIGO_CLASE = 110, @PESO = 5, @RANGO = 2, @UNIVERSO = @UNIVERSO_1 OUTPUT,
							@CANTIDAD_APROBADOS = @CANTIDAD_APROBADOS_1 OUTPUT, 
							@CANTIDAD_REPROBADOS = @CANTIDAD_REPROBADOS_1 OUTPUT;
SELECT @UNIVERSO_1 AS UNIVERSO, @CANTIDAD_APROBADOS_1 AS APROBADOS, @CANTIDAD_REPROBADOS_1 AS REPROBADOS;
--PRUEBA
SELECT ( @CANTIDAD_REPROBADOS_1/@UNIVERSO_1) * 100 AS  PORCENTAJE;