select * from UNAH.DBO.TBL_CALIFICACIONES;

select * from UNAH.DBO.TBL_CARRERAS_ESTUDIANTES;

select * from UNAH.DBO.TBL_CLASES;

select * from UNAH.DBO.TBL_CLASES_PLAN_ESTUDIOS;

select * from UNAH.DBO.TBL_DEPARTAMENTO;

select * from UNAH.DBO.TBL_EMPLEADOS;

select * from UNAH.DBO.TBL_FACULTAD;

select * from UNAH.DBO.TBL_INDICES;

select * from UNAH.DBO.TBL_PLAN_ESTUDIOS;

select * from UNAH.DBO.TBL_VALORACIONES_CLASES;

select * from UNAH.DBO.TBL_ESTUDIANTES ;


SELECT A.NUMERO_CUENTA ,A.P_NOMBRE+' '+A.S_NOMBRE AS 'NOMBRE COMPLETO',
	A.INDICE_GLOBAL ,B.NOMBRE_DEPARTAMENTO ,C.P_NOMBRE +''+C.S_NOMBRE AS 'JEFE DE DEPTO',
	D.P_NOMBRE +''+D.S_NOMBRE AS 'COORDINADOR DE DEPTO'
	FROM UNAH.DBO.TBL_ESTUDIANTES A
	INNER JOIN UNAH .DBO.TBL_DEPARTAMENTO  B
	ON(A.ID_DEPARTAMENTO =B.ID_DEPARTAMENTO )
	INNER JOIN UNAH .DBO.TBL_EMPLEADOS C
	ON(B.JEFE_DEPARTAMENTO  =C.ID_EMPLEADO )
	INNER JOIN UNAH .dbo .TBL_EMPLEADOS D
	ON(B.COORDINADOR_DEPARTAMENTO =D.ID_EMPLEADO ) ;

